wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.36
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
architecture:
  desc: null
  value: InceptionV3:avg
backbone:
  desc: null
  value: InceptionV3
batch_size:
  desc: null
  value: 32
min_samples:
  desc: null
  value: 320
pooling:
  desc: null
  value: avg
