wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.36
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
architecture:
  desc: null
  value: ResNet50:avg
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 60
kmeans_epochs:
  desc: null
  value: 1
update_interval:
  desc: null
  value: 5
